name: rtm
description: A Route To Market Sale Force Automation app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^8.0.3
  go_router: ^15.1.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.5.0
  path_provider: ^2.1.5
  supabase_flutter: ^2.9.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/app_icon/
  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/Graphik/Graphik Medium.otf
          weight: 500
        - asset: assets/fonts/Graphik/Graphik Semibold.otf
        - asset: assets/fonts/Graphik/GraphikBold.otf
          weight: 700
    - family: Helvetica Neue
      fonts:
        - asset: assets/fonts/Helvetica Neue/Helvetica Neue 67 Medium Condensed.otf
        - asset: assets/fonts/Helvetica Neue/Helvetica Neue Regular.otf
          weight: 500
        - asset: assets/fonts/Helvetica Neue/HelveticaNeue Medium.ttf
          weight: 600